config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  resources :books
  resources :camp_nights
  resources :adventures

  post 'load_teams' => 'teams#section_teams', as: :load_teams
  resources :teams, :except => [:index, :new, :create]
  resources :sections do
    resources :teams, :only => [:index, :new, :create]
  end

  patch '/photo_albums/:id/newphoto' => 'photo_albums#newphoto'
  resources :photos

  devise_for :users
  get 'pages/index'
  get 'contactos' => 'pages#contacts'
  get 'history' => 'pages#history'
  get 'maps' => 'pages#maps'

  get 'admin' => 'admin#index', as: :admin

  scope 'admin' do
    resources :users
    resources :posts do
      collection do
        get 'draft'
      end
      resources :categories
    end
    resources :people
  end

  get 'users/:id/roles' => 'users#roles', as: 'user_roles'
  patch 'users/:id/roles' => 'users#add_role'
  delete 'users/:id/roles' => 'users#remove_role'

  get 'alcateia' => 'pages#alcateia'
  get 'expedicao' => 'pages#expedicao'
  get 'comunidade' => 'pages#comunidade'
  get 'cla' => 'pages#cla'

  get 'blog' => 'blog#index', as: :blog
  get 'blog/:id' => 'blog#post', as: :blog_post

  resources :photo_albums, path: 'fotografias'

  resources :shop_products, :except => [:index]
  get 'shop' => 'shop_products#index'
  get 'shop/cart' => 'shop_products#show_cart', as: 'shopping_cart'
  get 'shop/:id/add_to_cart' => 'shop_products#add_to_cart', as: 'add_product_to_cart'
  get 'shop/:id/remove_from_cart' => 'shop_products#remove_from_cart', as: 'remove_product_from_cart'
  get 'shop/:id/delete_from_cart' => 'shop_products#delete_from_cart', as: 'delete_product_from_cart'

  resources :shop_orders
  get 'shop/orders' => 'shop_orders#user_index', as: 'user_shop_orders'
  get 'shop/:id/verify_payment' => 'shop_orders#verify_payment', as: 'verify_shop_order_payment'
  get 'shop/:id/ready' => 'shop_orders#ready', as: 'ready_shop_order'
  get 'shop/:id/finalize' => 'shop_orders#finalize', as: 'finalize_order'

  get 'calendario' => 'pages#calendar', as: :calendar
  get 'calendar/:year/:month' => 'pages#calendar'
  resources :events

  match "404/", :to => "errors#not_found", :via => :all
  match "500/", :to => "errors#internal_server_error", :via => :all
  root 'pages#index'

end

app/views/admin/_sidebar.html.erb
<div class='scroll fns' id="sidebar">
  <%= link_to admin_path do %>
    <svg role="img" title="logo">
      <use xlink:href="<%= image_path 'logo.svg' %>#logo"/>
    </svg>
  <% end %>

  <div class="stacked button-group">
    <% link_to "Ver Site", root_path, class: 'button', data: {turbolinks: false}, target: '_blank' %>
    <% active_link_to "Utilizadores", users_path, class: 'button' %>
    <%= active_link_to "Pessoas", people_path, class: 'button' %>
    <% active_link_to "Artigos", posts_path, class: 'button' %>
    <% active_link_to "Fotos", photo_albums_path, class: 'button' %>

    <%= link_to "Sair", destroy_user_session_path, class: 'button', method: :delete %>
  </div>
</div>

app/views/admin/_topbar.html.erb
<div id='topbar'>
  <h1><%= breadcrumbs %><%= title %></h1>
</div>

app/views/admin/index.html.erb
<% title 'Scouts Porto Salvo Admin' %>
<% breadcrumbs ({'Home' => admin_path}) %>

<%= link_to people_path, class: 'text-center admin-model-button' do %>
  <span>
    <%= fa_icon'users 2x' %><br>
    Pessoas
  </span>
<% end %>

app/views/admin/people.html.erb
<div class="row">
  <div class="columns">
    <h1><%= title "Administração de Pessoas" %></h1>
  </div>
</div>
<div class="row">
  <div class="columns">
    <ul class="button-group">
      <li><%= link_to "Adicionar", new_person_path, class: "button" %></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="columns">
    <%= render 'people/people_list' %>
  </div>
</div>

app/views/admin/posts.html.erb
<% title "Administração de Posts" %>

<%= link_to "Categorias", categories_path %>

<div class="row">
  <div class="columns">
    <%= render 'posts/posts_table' %>
  </div>
</div>

app/views/admin/users.html.erb
<div class="row">
  <div class="columns">
    <h1><%= title "Administração de Utilizadores" %></h1>
  </div>
</div>
<div class="row">
  <div class="columns">
    <%= render 'users/user_list' %>
  </div>
</div>