config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  resources :books
  resources :camp_nights
  resources :adventures

  post 'load_teams' => 'teams#section_teams', as: :load_teams
  resources :teams, :except => [:index, :new, :create]
  resources :sections do
    resources :teams, :only => [:index, :new, :create]
  end

  patch '/photo_albums/:id/newphoto' => 'photo_albums#newphoto'
  resources :photos

  devise_for :users
  get 'pages/index'
  get 'contactos' => 'pages#contacts'
  get 'history' => 'pages#history'
  get 'maps' => 'pages#maps'

  get 'admin' => 'admin#index', as: :admin

  scope 'admin' do
    resources :users
    resources :posts do
      collection do
        get 'draft'
      end
      resources :categories
    end
    resources :people
  end

  get 'users/:id/roles' => 'users#roles', as: 'user_roles'
  patch 'users/:id/roles' => 'users#add_role'
  delete 'users/:id/roles' => 'users#remove_role'

  get 'alcateia' => 'pages#alcateia'
  get 'expedicao' => 'pages#expedicao'
  get 'comunidade' => 'pages#comunidade'
  get 'cla' => 'pages#cla'

  get 'blog' => 'blog#index', as: :blog
  get 'blog/:id' => 'blog#post', as: :blog_post

  resources :photo_albums, path: 'fotografias'

  resources :shop_products, :except => [:index]
  get 'shop' => 'shop_products#index'
  get 'shop/cart' => 'shop_products#show_cart', as: 'shopping_cart'
  get 'shop/:id/add_to_cart' => 'shop_products#add_to_cart', as: 'add_product_to_cart'
  get 'shop/:id/remove_from_cart' => 'shop_products#remove_from_cart', as: 'remove_product_from_cart'
  get 'shop/:id/delete_from_cart' => 'shop_products#delete_from_cart', as: 'delete_product_from_cart'

  resources :shop_orders
  get 'shop/orders' => 'shop_orders#user_index', as: 'user_shop_orders'
  get 'shop/:id/verify_payment' => 'shop_orders#verify_payment', as: 'verify_shop_order_payment'
  get 'shop/:id/ready' => 'shop_orders#ready', as: 'ready_shop_order'
  get 'shop/:id/finalize' => 'shop_orders#finalize', as: 'finalize_order'

  get 'calendario' => 'pages#calendar', as: :calendar
  get 'calendar/:year/:month' => 'pages#calendar'
  resources :events

  match "404/", :to => "errors#not_found", :via => :all
  match "500/", :to => "errors#internal_server_error", :via => :all
  root 'pages#index'

end

app/models/shop_product.rb
class ShopProduct < ActiveRecord::Base
	has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/

	def price_str
		s = sprintf '%.2f €', self.price
		s.html_safe
	end
end

app/controllers/shop_products_controller.rb
class ShopProductsController < ApplicationController
	load_and_authorize_resource
	skip_authorize_resource :only => [:show_cart, :add_to_cart, :remove_from_cart, :delete_from_cart]

	before_action :set_shop_product, only: [:edit, :update, :destroy, :add_to_cart, :remove_from_cart, :delete_from_cart]
	before_action :authenticate_user!, only: [:add_to_cart, :show_cart]
	before_action :set_cart_product, only: [:add_to_cart, :remove_from_cart, :delete_from_cart]
	before_action :set_cart_products, only: [:show_cart]

	def index
		@shop_products = ShopProduct.all
	end

	def new
		@shop_product = ShopProduct.new
	end

	def create
		@shop_product = ShopProduct.new(shop_product_params)
		if @shop_product.save
			redirect_to shop_path
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @shop_product.update shop_product_params
			redirect_to shop_path
		else
			render :edit
		end
	end

	def destroy
		@shop_product.destroy
		redirect_to shop_path
	end

	def add_to_cart
		if @cart_product == nil
			# Product wasn't added to the cart
			@cart_product = current_user.shopping_cart_products.new
			@cart_product.shop_product = @shop_product
			@cart_product.quantity = 1
		else
			@cart_product.quantity = @cart_product.quantity + 1
		end
		@cart_product.save
		redirect_to :back, notice: @shop_product.name + ' adicionado ao carrinho'
	end

	def show_cart
	end

	def remove_from_cart
		@cart_product.quantity = @cart_product.quantity - 1
		if @cart_product.quantity < 1
			@cart_product.destroy
		else
			@cart_product.save
		end
		redirect_to :back, notice: '1 ' + @shop_product.name + ' removido ao carrinho'
	end

	def delete_from_cart
		@cart_product.destroy
		redirect_to :back, notice: @shop_product.name + ' removido ao carrinho'
	end

	private
	def shop_product_params
		params.require(:shop_product).permit(:name, :description, :price, :photo)
	end

	def set_shop_product
		@shop_product = ShopProduct.find params[:id]
	end

	def set_cart_products
		@cart_products = current_user.shopping_cart_products.where(shop_order: nil)
	end

	def set_cart_product
		@cart_product = current_user.shopping_cart_products.find_by(shop_order: nil, shop_product: @shop_product)
	end
end

app/helpers/shop_products_helper.rb
module ShopProductsHelper
	def products_in_cart
		nr_of_products = 0
		cart = current_user.shopping_cart_products.where(shop_order: nil)
		
		cart.each do |cart_product|
			nr_of_products += cart_product.quantity
		end

		nr_of_products
	end

	def cart_menu_string
		nr_of_products = products_in_cart
		menu_string = "Carrinho"
		unless nr_of_products == 0
			menu_string += " ( #{nr_of_products} )"
		end
		menu_string
	end

	def decimal_to_euro(decimal)
		s = sprintf '%.2f €', decimal
		s.html_safe
	end

	def cart_product_total(cart_product)
		price = cart_product.shop_product.price
		total = price * cart_product.quantity
	end

	def cart_total(cart)
		total = 0
		cart.each do |cart_product|
			total += cart_product_total cart_product
		end
		total
	end
end

app/views/shop_products/_form.html.erb
<%= form_for @shop_product do |f| %>
	<%= f.label :name, "Nome" %>
	<%= f.text_field :name %>
	<%= f.label :description, "Descrição" %>
	<%= f.text_area :description %>
	<%= f.label :price, "Preço" %>
	<%= f.number_field :price, class: "text_field", step: '0.01' %>
	<%= f.label :photo %>
	<%= f.file_field :photo, as: :file %>
	<%= f.submit class: "button" %>
<% end %>

app/views/shop_products/_top_menu.html.erb
<ul class="button-group radius">
  <li><%= link_to 'Loja', shop_path, class: "button small" %></li>

  <% if can? :create, ShopProduct %>
    <li><%= link_to 'Novo', new_shop_product_path, class: "button small" %></li>
  <% end %>

  <li><%= link_to 'Encomendas', user_shop_orders_path, class: "button small" %></li>

  <% if user_signed_in? %>
    <li><%= link_to cart_menu_string, shopping_cart_path, class: "button small" %></li>
  <% end %>

  <% if can? :manage, ShopOrder %>
    <li><%= link_to 'Pendentes', shop_orders_path, class: "button small" %></li>
  <% end %>
</ul>

app/views/shop_products/edit.html.erb
<div class='content'>
	<div class="row">
		<div class="columns">
			<h1><%= title "Editar Produto" %></h1>
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/shop_products/index.html.erb
<div class="row">
  <div class="columns">
    <%= render "top_menu" %>
  </div>
</div>
<div class="row" data-equalizer>
  <% count = 0 %>
  <% @shop_products.each do |product| %>
    <div class="columns medium-4 large-4 end" data-equalizer-watch>
      <div class="panel radius">
        <%= image_tag product.photo.url(:medium) %>
        <h2><%= product.name %></h2>
        <%= simple_format product.description %>
        <p><strong><%= product.price_str %></strong></p>
        <ul class="stack button-group radius">
          <li><%= link_to 'Adicionar', add_product_to_cart_path(product), class: "button expand" %></li>
          <% if can? :update, ShopProduct %>
            <li><%= link_to 'Editar', edit_shop_product_path(product), class: "button info" %></li>
            <li><%= link_to 'Eliminar', product, method: :delete, class: "button alert" %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <% count += 1 %>
    <% if count == 3 %>
      </div>
      <div class="row" data-equalizer>
    <% end %>
  <% end %>
</div>

app/views/shop_products/new.html.erb
<div class='content'>
	<div class="row">
		<div class="columns">
			<h1><%= title "Novo Produto" %></h1>
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/shop_products/show_cart.html.erb
<div class='content'>
	<div class="row">
		<div class="columns medium-6 small-6">
			<h1><%= title "Carrinho de Compras" %></h1>
		</div>
		<div class="columns medium-6 small-6 text-right">
			<%= render "top_menu" %>
		</div>
	</div>
	<div class="row">
		<div class="columns">
			<% if @cart_products.length > 0 %>
				<table>
					<thead class="hidden-for-small-only">
						<th width=200>Produto</th>
						<th width=100>Preço</th>
						<th>Quantidade</th>
						<th>Total</th>
						<th></th>
					</thead>
					<tbody>
						<% @cart_products.each do |cart_product| %>
							<tr>
								<td><%= cart_product.shop_product.name %></td>
								<td class="text-right"><%= cart_product.shop_product.price_str %></td>
								<td class="text-center">
									<%= link_to "-", remove_product_from_cart_path(cart_product.shop_product), class: "label" %>
									<span class="label info"><%= cart_product.quantity %></span>
									<%= link_to "+", add_product_to_cart_path(cart_product.shop_product), class: "label" %>
								</td>
								<td class="text-right"><%= decimal_to_euro(cart_product_total cart_product) %></td>
								<td><%= link_to "X", delete_product_from_cart_path(cart_product.shop_product), class: "alert label", data: { confirm: "Pretende remover este(s) item(s) do carrinho?" } %></td>
							</tr>
						<% end %>
					</tbody>
				</table>
				<h3>Total: <%= decimal_to_euro(cart_total @cart_products) %></h3>
				<%= link_to "Finalizar compra", shop_orders_path, class: "button", method: "post" %>
			<% end %>
		</div>
	</div>
</div>