config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  resources :books
  resources :camp_nights
  resources :adventures

  post 'load_teams' => 'teams#section_teams', as: :load_teams
  resources :teams, :except => [:index, :new, :create]
  resources :sections do
    resources :teams, :only => [:index, :new, :create]
  end

  patch '/photo_albums/:id/newphoto' => 'photo_albums#newphoto'
  resources :photos

  devise_for :users
  get 'pages/index'
  get 'contactos' => 'pages#contacts'
  get 'history' => 'pages#history'
  get 'maps' => 'pages#maps'

  get 'admin' => 'admin#index', as: :admin

  scope 'admin' do
    resources :users
    resources :posts do
      collection do
        get 'draft'
      end
      resources :categories
    end
    resources :people
  end

  get 'users/:id/roles' => 'users#roles', as: 'user_roles'
  patch 'users/:id/roles' => 'users#add_role'
  delete 'users/:id/roles' => 'users#remove_role'

  get 'alcateia' => 'pages#alcateia'
  get 'expedicao' => 'pages#expedicao'
  get 'comunidade' => 'pages#comunidade'
  get 'cla' => 'pages#cla'

  get 'blog' => 'blog#index', as: :blog
  get 'blog/:id' => 'blog#post', as: :blog_post

  resources :photo_albums, path: 'fotografias'

  resources :shop_products, :except => [:index]
  get 'shop' => 'shop_products#index'
  get 'shop/cart' => 'shop_products#show_cart', as: 'shopping_cart'
  get 'shop/:id/add_to_cart' => 'shop_products#add_to_cart', as: 'add_product_to_cart'
  get 'shop/:id/remove_from_cart' => 'shop_products#remove_from_cart', as: 'remove_product_from_cart'
  get 'shop/:id/delete_from_cart' => 'shop_products#delete_from_cart', as: 'delete_product_from_cart'

  resources :shop_orders
  get 'shop/orders' => 'shop_orders#user_index', as: 'user_shop_orders'
  get 'shop/:id/verify_payment' => 'shop_orders#verify_payment', as: 'verify_shop_order_payment'
  get 'shop/:id/ready' => 'shop_orders#ready', as: 'ready_shop_order'
  get 'shop/:id/finalize' => 'shop_orders#finalize', as: 'finalize_order'

  get 'calendario' => 'pages#calendar', as: :calendar
  get 'calendar/:year/:month' => 'pages#calendar'
  resources :events

  match "404/", :to => "errors#not_found", :via => :all
  match "500/", :to => "errors#internal_server_error", :via => :all
  root 'pages#index'

end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :teams
  has_many :people
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  load_and_authorize_resource
  layout 'admin'

  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:name, :description, :public)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :public %><br>
    <%= f.check_box :public %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<% title @section.name %>

<% content_for :back_link do %>
  <%= section_path @section %>
<% end %>

<%= render 'form' %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<% title 'Secções' %>

<%= render 'people/submenu' %>

<%= link_to fa_icon('plus', text: 'Adicionar'), new_section_path, class: 'button' %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.name %></td>
        <td><%= section.description %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'people/submenu' %>

<%= render 'form' %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<% title @section.name %>

<% content_for :back_link do %>
  <%= sections_path %>
<% end %>

<% if can? :update, @section %>
  <%= render partial: 'pages/page_action', locals: { link: edit_section_path(@section), icon: 'pencil' } %>
<% end %>

<div class='card card-3'>
  <div class='card-content'>
    <%= safe_markdown @section.description %>
  </div>
</div>

<h1>Patrulhas</h1>
<div class="row">
  <% @section.teams.each do |team| %>
    <div class="columns medium-4 end">
      <div class='card card-3'>
        <div class='card-content'>
          <h2><%= team.name %></h2>
          <ul>
            <% team.people.each do |person| %>
              <li><%= link_to person.name, person %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'Nova Equipa', new_section_team_path(@section) %>