config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  resources :books
  resources :camp_nights
  resources :adventures

  post 'load_teams' => 'teams#section_teams', as: :load_teams
  resources :teams, :except => [:index, :new, :create]
  resources :sections do
    resources :teams, :only => [:index, :new, :create]
  end

  patch '/photo_albums/:id/newphoto' => 'photo_albums#newphoto'
  resources :photos

  devise_for :users
  get 'pages/index'
  get 'contactos' => 'pages#contacts'
  get 'history' => 'pages#history'
  get 'maps' => 'pages#maps'

  get 'admin' => 'admin#index', as: :admin

  scope 'admin' do
    resources :users
    resources :posts do
      collection do
        get 'draft'
      end
      resources :categories
    end
    resources :people
  end

  get 'users/:id/roles' => 'users#roles', as: 'user_roles'
  patch 'users/:id/roles' => 'users#add_role'
  delete 'users/:id/roles' => 'users#remove_role'

  get 'alcateia' => 'pages#alcateia'
  get 'expedicao' => 'pages#expedicao'
  get 'comunidade' => 'pages#comunidade'
  get 'cla' => 'pages#cla'

  get 'blog' => 'blog#index', as: :blog
  get 'blog/:id' => 'blog#post', as: :blog_post

  resources :photo_albums, path: 'fotografias'

  resources :shop_products, :except => [:index]
  get 'shop' => 'shop_products#index'
  get 'shop/cart' => 'shop_products#show_cart', as: 'shopping_cart'
  get 'shop/:id/add_to_cart' => 'shop_products#add_to_cart', as: 'add_product_to_cart'
  get 'shop/:id/remove_from_cart' => 'shop_products#remove_from_cart', as: 'remove_product_from_cart'
  get 'shop/:id/delete_from_cart' => 'shop_products#delete_from_cart', as: 'delete_product_from_cart'

  resources :shop_orders
  get 'shop/orders' => 'shop_orders#user_index', as: 'user_shop_orders'
  get 'shop/:id/verify_payment' => 'shop_orders#verify_payment', as: 'verify_shop_order_payment'
  get 'shop/:id/ready' => 'shop_orders#ready', as: 'ready_shop_order'
  get 'shop/:id/finalize' => 'shop_orders#finalize', as: 'finalize_order'

  get 'calendario' => 'pages#calendar', as: :calendar
  get 'calendar/:year/:month' => 'pages#calendar'
  resources :events

  match "404/", :to => "errors#not_found", :via => :all
  match "500/", :to => "errors#internal_server_error", :via => :all
  root 'pages#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  alias_attribute :author, :user
  has_and_belongs_to_many :categories

  accepts_nested_attributes_for :categories

  has_attached_file :image, styles: {thumb: "150x150^", large: "1080x1080^", medium: "600x600>" }, default_url: "/escuteiro.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  def to_html(renderer)
    markdown = Redcarpet::Markdown.new(renderer, extensions = {})
    markdown.render(self.body)
  end

  def markdown_to_html(markdown)
    markdown.render(self.body)
  end

  def publish(args)
    self.published_at = DateTime.now
    self.draft = false
    args[:draft] = "0"
    self.update args
  end

  # Overrides
  def update(args)
    if self.draft and args[:draft] == "0"
      publish args
    else
      super args
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  layout 'admin'

  before_action :set_post, only: [:show, :edit, :update]

  def index
    @posts = Post.where(draft: false).paginate(:page => params[:page], :per_page => 5)
  end

  def draft
    @posts = Post.where(draft: true).paginate(:page => params[:page], :per_page => 5)
    render :index
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.published_at = @post.created_at
    if @post.save
      redirect_to @post, notice: "Artigo '#{@post.title}' publicado"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  private
  def post_params
    params.require(:post).permit(:draft, :image, :title, :body, { category_ids: [] } )
  end

  def set_post
    @post = Post.find params[:id]
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def safe_markdown(content)
    @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, fenced_code_blocks: true, tables: true)
    @markdown.render(content).html_safe
  end 
end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="card-content">
    <div class="row">
      <div class="columns small-6">
        <%= f.file_field :image, as: :file %>
      </div>
      <div class="columns small-6 text-right">
        <div class="row">
          <div class="columns small-10">
            <%= f.label :draft, 'Rascunho' %>
          </div>
          <div class="columns small-2">
            <%= f.check_box :draft, prompt: 'Rascunho' %>
          </div>
        </div>
      </div>
    </div>
    <%= f.label :title, "Título" %>
    <%= f.text_field :title %>
    <%= f.label :body, "Texto" %>
    <%= f.text_area :body, rows: 15 %>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name, {prompt: 'Categorias'} %><br>
  </div>
  <%= f.submit class: "button first last" %>
<% end %>

app/views/posts/_posts_list.html.erb
<% @posts.each do |post| %>
  <div class="card card-3">
    <%= link_to image_tag(post.image.url(:medium), class: 'header large'), post if post.image.exists? %>
    <div class="card-content">
      <h2><%= link_to post.title, post %> <small><%= l post.published_at.to_date, format: :short %></small></h2>
      <p><%= truncate strip_tags(safe_markdown post.body), length: 250 %></p>
      <small><%= post.user.name %></small>
    </div>

    <div class="card-action">
      <div class="row collapse">
        <div class="columns small-6">
          <%= link_to fa_icon('share-alt'), "", title: 'Partilhar', class: 'button first', id: "fb#{post.id}" %>
          <script>
            $("#fb<%= post.id %>").on("click",function(){
              var fbpopup = window.open("https://www.facebook.com/sharer/sharer.php?u=<%= post_url post %>", "pop", "width=600, height=400, scrollbars=no");
              return false;
            });
          </script>
        </div>

        <div class="columns small-6">
          <%= link_to "LER MAIS", post, class: 'button last' %>
        </div>
      </div>
    </div>
  </div>
<% end %>
<div id="fb-root"></div>

app/views/posts/_posts_table.html.erb
<table>
	<thead>
		<tr>
			<th>Título</th>
			<th>Autor</th>
			<th>Ações</th>
		</tr>
	</thead>
	<tbody>
		<% @posts.each do |post| %>
			<tr>
				<td><%= link_to post.title, post %></td>
				<td><%= link_to post.user.email, post.user %></td>
				<td><%= link_to "Eliminar", post, method: :delete, data: {confirm: "Tem a certeza que pretende eliminar o post: #{post.title}?"} %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/posts/_small_post.html.erb
<h2><%= @post.title %></h2>
<%= simple_format @post.body %>
<small><%= "#{@post.user.email} a #{@post.created_at.strftime('%-d/%m/%y')}" %></small>

app/views/posts/blog.html.erb
<% title "Blog" %>

<% content_for :back_link do %>
  <%= root_path %>
<% end %>

<% content_for :subtitle do %>
  <%= will_paginate @posts, previous_label: '', next_label: '' %>
<% end %>

<div class="row">
  <div class="columns">
    <%= render 'posts_list' %>
    <%= will_paginate @posts, page_links: false, previous_label: '', next_label: '' %>
  </div>
</div>

app/views/posts/edit.html.erb
<% title "Editar Artigo" %>

<% content_for :subtitle do %>
  <%= @post.title %>
<% end %>

<% content_for :back_link do %>
  <%= post_path @post %>
<% end %>

<div class="columns">
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% title "Artigos" %>

<% content_for :submenu do %>
  <%= active_link_to fa_icon('check', text: 'Artigos'), posts_path, class: 'button', active: :exclusive %>
  <%= active_link_to fa_icon('file-text', text: 'Rascunhos'), draft_posts_path, class: 'button', active: :exclusive %>
  <%= active_link_to fa_icon('plus', text: 'Novo'), new_post_path, class: 'button', active: :exclusive %>
<% end %>

<% content_for :back_link do %>
  <%= root_path %>
<% end %>

<% content_for :subtitle do %>
  <%= will_paginate @posts, previous_label: '', next_label: '' %>
<% end %>

<div class="row">
  <div class="columns">
    <table>
      <thead>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
          <tr data-url="<%= edit_post_path post %>">
            <td class='image'><%= image_tag post.image.url(:thumb) %></td>
            <td><div><%= post.title %></div></td>
            <td><div><%= post.author.name %></div></td>
            <td class="text-right"><div><%= post.published_at %></div></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @posts, page_links: false, previous_label: '', next_label: '' %>
  </div>
</div>

app/views/posts/new.html.erb
<% title "Novo Artigo" %>

<% content_for :submenu do %>
  <%= active_link_to fa_icon('check', text: 'Artigos'), posts_path, class: 'button', active: :exclusive %>
  <%= active_link_to fa_icon('file-text', text: 'Rascunhos'), draft_posts_path, class: 'button', active: :exclusive %>
  <%= active_link_to fa_icon('plus', text: 'Novo'), new_post_path, class: 'button', active: :exclusive %>
<% end %>

<% content_for :back_link do %>
  <%= posts_path %>
<% end %>

<div class="row">
  <div class="columns">
    <h1></h1>
    <%= render 'form' %>
  </div>
</div>

app/views/posts/show.html.erb
<% 
  set_meta_tags og: {
    title:    @post.title,
    description: truncate(strip_tags(safe_markdown @post.body), length: 250),
    type:     'article',
    url:      post_url(@post),
    image:    asset_url(@post.image.url),
  }
%>
<% title @post.title %>

<% content_for :subtitle do %>
  Por <%= @post.author.name %>
<% end %>

<% content_for :back_link do %>
  <%= posts_path %>
<% end %>

<% if can? :update, @post %>
  <%= render partial: 'pages/page_action', locals: { link: edit_post_path(@post), icon: 'pencil' } %>
<% end %>

<div class="row">
  <div class="columns">
    <div class="card card-3">
      <%= image_tag @post.image.url(:medium), class: 'header' if @post.image.exists? %>
      <div class="card-content">
        <%= safe_markdown(@post.body) %>
        <small><%= "Criado a #{@post.published_at.strftime('%-d/%m/%y')}" if not @post.draft %></small>
      </div>
    </div>
    <% if can? :destroy, @post %>
      <%= link_to "Eliminar", @post, class: "button tiny", method: :delete, data: {confirm: "Tem a certeza que pretende eliminar este Post?"} %>
    <% end %>
  </div>
</div>